[package]
name = "bcfbh"
version = "0.1.1"
edition = "2024"
description = "Booklet Creator For Binding by Hand"

[dependencies]
oxidize-pdf = "1.6.13"
pdfium-render = "0.8.37"
image = "0.25"

[profile.release]
lto = true
strip = true
panic = "abort"